default:
  tags:
    - ci.inria.fr # required to run on shared gitlab.inria.fr runners

stages:
  - build
  - test

###
## Build
#

build application:
  stage: build
  image: node:14-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "dist"
  when: manual

###
## Test
#

.e2e:
  image: docker:20.10.12-dind
  stage: test
  except:
    - schedules
  variables:
    DOCKERFILE_PATH: src/e2e/Dockerfile
    BUILD_IMAGE: 'docker build -f $DOCKERFILE_PATH -t $IMAGE --no-cache .' 
    RUN_CI_CONTAINER: 'docker run --privileged -d --name $CONTAINER $IMAGE'
    RUN_MUTE_SIGVER: 'docker exec -w /app/mute $CONTAINER /bin/sh start-mute-sigver-containers.sh'
    STOP_CI_CONTAINER: 'docker stop $CONTAINER'
    RUN_TEST: 'docker exec -w /app/ci $CONTAINER npm run test chromium firefox $SCENARIO true'
  before_script:
    - $BUILD_IMAGE
    - $RUN_CI_CONTAINER
    - sleep 10
    - $RUN_MUTE_SIGVER
  script:
    - $RUN_TEST

e2e full scenario:
  extends: .e2e
  variables: 
    IMAGE: ci-full-scenario
    CONTAINER: ci-full-scenario-container
    SCENARIO: fullscenario
  after_script:
    - $STOP_CI_CONTAINER
  when: manual

e2e online scenario:
  extends: .e2e
  variables: 
    IMAGE: ci-online-scenario
    CONTAINER: ci-online-scenario-container
    SCENARIO: online
  after_script:
    - $STOP_CI_CONTAINER

e2e offline scenario:
  extends: .e2e
  variables: 
    IMAGE: ci-offline-scenario
    CONTAINER: ci-offline-scenario-container
    SCENARIO: offline
  after_script:
    - $STOP_CI_CONTAINER

e2e offline-to-online scenario:
  extends: .e2e
  variables: 
    IMAGE: ci-offline-to-online-scenario
    CONTAINER: ci-offline-to-online-scenario-container
    SCENARIO: offline-to-online
