version: '3.9'

services:

  mute:
    image: mute
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:${MUTE_PORT:-4200}
    depends_on:
      - sigver

  sigver:
    image: sigver
    build:
      context: .
      dockerfile: DockerfileSigver
    ports:
      - 8010:${SIGVER_PORT:-8010}

  pulsar:
    profiles:
      - pulsar
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 8080:${PULSAR_WEB_PORT:-8080}
      - 6650:${PULSAR_PORT:-6650}
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone

volumes:
  pulsardata:
  pulsarconf: