version: '3.9'

services:

  mute:
    image: ${MUTE_IMAGE:-registry.gitlab.inria.fr/coast-team/mute/mute}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${MUTE_PORT:-4200}:4200
    depends_on:
      - sigver

  sigver:
    image: ${SIGVER_IMAGE:-registry.gitlab.inria.fr/coast-team/mute/mute/sigver}
    build:
      context: .
      dockerfile: DockerfileSigver
    ports:
      - ${SIGVER_PORT:-8010}:8010

  libp2p-signaling-server:
    image: libp2p-webrtc-star-signaling-server
    build:
      context: .
      dockerfile: DockerfileWebRTCStarSignalingServer
    ports:
      - 8015:8015

  pulsar:
    profiles:
      - pulsar
    image: docker.io/apachepulsar/pulsar:2.6.0
    ports:
      - ${PULSAR_WEB_PORT:-8080}:8080
      - ${PULSAR_PORT:-6650}:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone

volumes:
  pulsardata:
  pulsarconf: