# This workflow will comment the triggering PR with a bundle size analysis
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Bundle size analysis

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}